- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Yum update
    command: sudo yum update
  - name: Install Docker
    command: sudo yum install docker -y
  - name: Docker Start
    command: sudo systemctl start docker
  - name: Deploy Medicure Docker Image
    command: sudo docker run -itd -p 8089:8081 --name healthcare build -t udaydocker123/medicureproject
